In [1]:
import numpy as np

# 1
arr_true = np.ones((3,3), dtype=bool)
print(arr_true)

# 2
arr_1D = np.arange(9)
arr_2D = arr_1D.reshape(3,3)
print(arr_2D)

# 3
arr_col_swap = arr_2D.copy()
arr_col_swap[:, [0,2]] = arr_col_swap[:, [2,0]]
print(arr_col_swap)

arr_row_swap = arr_2D.copy()
arr_row_swap[[0,1]] = arr_row_swap[[1,0]]
print(arr_row_swap)

# 4
print(arr_2D[::-1])

# 5
print(arr_2D[:, ::-1])

# 6
arr_null = np.array([[1,2,3],[np.nan,5,6],[7,np.nan,9]])
print("Has NaN:", np.isnan(arr_null).any())
print("Filled:", np.nan_to_num(arr_null, nan=0))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
Has NaN: True
Filled: [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]]
